"""updated userprogram schema to be less complicated

Revision ID: e72fc3be6329
Revises: 29b6e0bd347f
Create Date: 2025-03-20 09:15:36.729072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72fc3be6329'
down_revision = '29b6e0bd347f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_undergrad', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('major', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('concentrations', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('minor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('credits_min', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('gpa_min', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('concentration_needed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('minor_needed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('calendar_type', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('coop_type', sa.Boolean(), nullable=False))
        batch_op.drop_column('user_major')
        batch_op.drop_column('user_concentration_needed')
        batch_op.drop_column('user_credit_min')
        batch_op.drop_column('user_gpa_min')
        batch_op.drop_column('undergrad')
        batch_op.drop_column('user_minor_needed')
        batch_op.drop_column('user_calendar_type')
        batch_op.drop_column('user_coop_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_coop_type', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_calendar_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_minor_needed', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('undergrad', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_gpa_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_credit_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_concentration_needed', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_major', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('coop_type')
        batch_op.drop_column('calendar_type')
        batch_op.drop_column('minor_needed')
        batch_op.drop_column('concentration_needed')
        batch_op.drop_column('gpa_min')
        batch_op.drop_column('credits_min')
        batch_op.drop_column('minor')
        batch_op.drop_column('concentrations')
        batch_op.drop_column('major')
        batch_op.drop_column('is_undergrad')

    # ### end Alembic commands ###
