"""initial migration

Revision ID: f11435132c1e
Revises: 
Create Date: 2025-02-26 11:38:11.772097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11435132c1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('drexel_email', sa.String(length=60), nullable=False),
    sa.Column('hashed_password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_pid', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_pid'], ['users.pid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_pid', sa.Integer(), nullable=False),
    sa.Column('user_interests', sa.String(length=255), nullable=True),
    sa.Column('user_timing', sa.String(length=255), nullable=True),
    sa.Column('user_goals', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['student_pid'], ['users.pid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_pid', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('graduation_date', sa.Date(), nullable=False),
    sa.Column('undergrad', sa.Boolean(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('user_major', sa.String(length=255), nullable=False),
    sa.Column('user_credit_min', sa.Float(), nullable=False),
    sa.Column('user_gpa_min', sa.Float(), nullable=False),
    sa.Column('user_concentration_needed', sa.Boolean(), nullable=False),
    sa.Column('user_minor_needed', sa.Boolean(), nullable=False),
    sa.Column('user_calendar_type', sa.String(length=255), nullable=False),
    sa.Column('user_coop_type', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_pid'], ['users.pid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_term_planning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_pid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_pid'], ['users.pid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_term_planning')
    op.drop_table('user_program')
    op.drop_table('user_preferences')
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
